apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: app-gateway
    kind: Deployment
  minReplicas: 2
  maxReplicas: 4
  # targetCPUUtilizationPercentage: 25