apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 1Deployment.yaml
- 2Deployment-beta.yaml
- 3Service.yaml
- 5DestinationRule.yaml
- 6IngressGateway.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 14f06f8843422fd79ab0a0a201bfaf2897846cbe